### ISSUE TITLE
Train with fine-tuned embeddings?

### ISSUE THREAD

**Issue by ayanyuegupta** [yanzhangnlp/IS-BERT#2]
Hi,

Thanks very much for releasing your code!

Was wondering if it is worth training IS-BERT with a fine-tuned hugging face model rather than with an out-of-the-box hugging face model?

So, if I want to train IS-BERT on reddit comments, is it better to:

a.) Fine-tune 'bert-base-uncased' on reddit comments and then use embeddings from fine-tuned model to train IS-BERT

or

b.) Directly train IS-BERT on reddit comments using 'bert-base-uncased' embeddings _without_ first fine-tuning 'bert-base-uncased' on reddit comments?

**Comment by yanzhangnlp** [comment]
Thank you for your interest in our work. Training IS-BERT on NLI using 'bert-base-uncased' embeddings performs better than fine-tuning 'bert-base-uncased' on the STS tasks.  However,  I have not tried a) yet and I suggest you can try both.
